name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 3.2.3
  EXPORT_NAME: test-project

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: false
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot -v --export "HTML5" build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web
      - name: LS a bunch of places
        run: |
          ls -al .
          ls -al build/web
          ls -al web
      - name: SCP Upload to Mickey's Server 🚀🚀
        # You may pin to the exact commit or the version.
        # uses: betanzos/scp-upload@4afbc824f4b0940d2b1ae862590033424385e3ab
        uses: appleboy/scp-action@master
        with:
          # Source local file path
          source: "web/*"
          # Remote host
          host: box.mickeyhl.li
          # Remote host SSH port
          port: 22 # optional, default is 22
          # Remote host username
          username: ubuntu
          # SSH private key
          key: ${{ secrets.PRIVATE_KEY_MICKEY_SERVER }}
          passphrase: ${{ secrets.PRIVATE_KEY_MICKEY_SERVER_PASSPHRASE }}
          # Remote directory to copy the file
          target: "/home/user-data/website/repo/public/game-html/"

